- name: Clean up previous build
  shell: >
    cd {{ sx_repo_dir }} &&
    git clean -xfd

- name: Build Skylable SX
  shell: >
    cd {{ sx_repo_dir }} &&
    ./configure --prefix={{ sx_build_dir }} {% if nss_check.rc == 0 %}--with-nss{% endif %}&&
    make -j {{ ansible_processor_vcpus }} &&
    make install

- name: Store build stamp
  shell: >
    cd {{ sx_repo_dir }} &&
    git describe --always > {{ sx_build_stamp_path }}
