- name: Install Skylable SX dependencies (apt)
  when: ansible_pkg_mgr == 'apt'
  apt: name={{item}} state=installed
  with_items:
    - make
    - gcc
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libssl-dev
    - git

- name: Install Skylable SX dependencies (yum)
  when: ansible_pkg_mgr == 'yum'
  yum: name={{ item }} state=installed
  with_items:
    - make
    - gcc
    - libcurl-devel
    - zlib-devel
    - openssl-devel
    - fuse-devel
    - git

- name: Clone Skylable SX git repository
  git: repo=http://git.skylable.com/sx dest={{ sx_repo_dir }} version={{ sx_build_commit }}

- name: Get build stamp of current checkout
  shell: "cd {{ sx_repo_dir }}; git describe --always"
  register: sx_new_build_stamp

- name: Get build stamp of last Skylable SX build
  shell: "cat {{ sx_build_stamp_path }} || echo"
  register: sx_last_build_stamp

- debug: msg="{{ sx_last_build_stamp.stdout }} -> {{ sx_new_build_stamp.stdout }}"

- include: build-sx.yml
  when: sx_new_build_stamp.stdout != sx_last_build_stamp.stdout
