- name: Install Skylable SX dependencies (apt)
  when: ansible_pkg_mgr == 'apt'
  apt: name={{item}} state=installed
  with_items:
    - make
    - gcc
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libssl-dev
    - git
    - fuse
    - libfuse-dev
    - file

- name: Install Skylable SX dependencies (yum)
  when: ansible_pkg_mgr == 'yum'
  yum: name={{ item }} state=installed
  with_items:
    - make
    - gcc
    - zlib-devel
    - openssl-devel
    - fuse-devel
    - git
    - file

- name: Determine the name of curl dependency package (yum)
  when: ansible_pkg_mgr == 'yum'
  command: yum info libcurl-devel
  args:
    warn: no  # mute the suggestion to use yum module
  register: libcurl_check
  failed_when: false

- name: Install Skylable SX curl dependency (yum)
  when: ansible_pkg_mgr == 'yum'
  yum: name="{% if libcurl_check.rc == 0 %}libcurl-devel{% else %}curl-devel{% endif %}" state=installed

- name: Detect NSS
  shell: curl --version | grep -w NSS
  args:
    warn: no  # mute the suggestion to use get_url module
  register: nss_check
  changed_when: false
  failed_when: "{{ nss_check.rc == 2 }}"

- name: Install NSS dependency (yum)
  when:
    - ansible_pkg_mgr == 'yum'
    - nss_check.rc == 0
  yum: name=nss-devel state=installed

- name: Clone Skylable SX git repository
  git: repo=http://git.skylable.com/sx dest={{ sx_repo_dir }} version={{ sx_build_version }}

- name: Get build stamp of current checkout
  shell: "cd {{ sx_repo_dir }}; git describe --always"
  register: sx_new_build_stamp
  changed_when: false

- name: Get build stamp of last Skylable SX build
  shell: "cat {{ sx_build_stamp_path }} || echo"
  register: sx_last_build_stamp
  changed_when: false

- debug: msg="{{ sx_last_build_stamp.stdout }} -> {{ sx_new_build_stamp.stdout }}"

- include: build-sx.yml
  when: sx_new_build_stamp.stdout != sx_last_build_stamp.stdout
