- name: Confirm existence of etc/ssl/private dir
  file:
    path: "{{ sx_build_prefix }}/etc/ssl/private"
    state: directory

- name: Confirm existence of etc/ssl/certs dir
  file:
    path: "{{ sx_build_prefix }}/etc/ssl/certs"
    state: directory
    follow: yes

- name: Create SSL certificate configuration
  template:
    src: cert.j2
    dest: "{{ sx_lib_dir }}/openssl.cnf"
  when: is_first_node|bool

- name: Generate SSL certificate
  command: >
      openssl req -days {{ cert_validity }} -x509
      -config {{ sx_lib_dir }}/openssl.cnf -new
      -keyout {{ sx_build_prefix }}/etc/ssl/private/sxkey.pem
      -out {{ sx_build_prefix }}/etc/ssl/certs/sxcert.pem
  args:
    creates: "{{ sx_build_prefix }}/etc/ssl/private/sxkey.pem"
  when: is_first_node|bool

- name: Download SSL key
  slurp: "src={{ sx_build_prefix }}/etc/ssl/private/sxkey.pem"
  register: ssl_key
  when: is_first_node|bool

- name: Download SSL certificate
  slurp: "src={{ sx_build_prefix }}/etc/ssl/certs/sxcert.pem"
  register: ssl_cert
  when: is_first_node|bool

- name: Check if SSL key file exists
  stat:
    path: "{{ sx_build_prefix }}/etc/ssl/private/sxkey.pem"
  register: sxkey_stat

- name: Upload SSL key file
  copy:
    content: "{{ hostvars[first_node_name].ssl_key.content|b64decode }}"
    dest: "{{ sx_build_prefix }}/etc/ssl/private/sxkey.pem"
    owner: "{{ sx_server_user }}"
    group: "{{ sx_server_group }}"
    mode: 0600
    force: no
  when: not sxkey_stat.stat.exists

- name: Check if SSL cert file exists
  stat:
    path: "{{ sx_build_prefix }}/etc/ssl/certs/sxcert.pem"
  register: sxcert_stat

- name: Upload SSL cert file
  copy:
    content: "{{ hostvars[first_node_name].ssl_cert.content|b64decode }}"
    dest: "{{ sx_build_prefix }}/etc/ssl/certs/sxcert.pem"
    owner: "{{ sx_server_user }}"
    group: "{{ sx_server_group }}"
    mode: 0600
    force: no
  when: not sxcert_stat.stat.exists
